---
title: "golem hook"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-1}
# Load already included functions
pkgload::load_all(export_all = FALSE)
```

# My function

```{r function-my_fun}
#' Golem Hook function
#'
#' @return Used for side effect
#' @inheritParams golem::project_hook
#' @export
#'
#' @examples
golem_hook <- function(path, package_name, ...) {
  unlink("R/run_app.R", TRUE, TRUE)
  unlink("R/app_ui.R", TRUE, TRUE)
  unlink("R/app_server.R", TRUE, TRUE)
  
  file.copy(
    system.file(
      "golem/run_app.R",
      package = "brochure"
    ),
    "R/run_app.R"
  )
  # Include `package_name` as `app_title` in in run_app()
  run_app <- readLines(
    "R/run_app.R"
  )
  run_app <- gsub(
    "REPLACEME",
    package_name,
    run_app
  )
  write(run_app, "R/run_app.R")
  
  file.copy(
    system.file(
      "golem/mod_home.R",
      package = "brochure"
    ),
    "R/mod_home.R"
  )
  
  dev_R <- readLines(
    "dev/02_dev.R"
  )
  dev_R[
    which(
      grepl(
        "name_of_module1",
        dev_R
      )
    )
  ] <- 'golem::add_module(name = "name_of_module1", with_test = TRUE, module_template = brochure::new_page) # Name of the module'
  
  dev_R[
    which(
      grepl(
        "name_of_module2",
        dev_R
      )
    )
  ] <- 'golem::add_module(name = "name_of_module2", with_test = TRUE, module_template = brochure::new_page) # Name of the module'
  unlink("dev/02_dev.R")
  write(dev_R, "dev/02_dev.R")
}
```

```{r examples-my_fun}
if (requireNamespace("golem") & interactive()) {
  golem::create_golem("myapp", project_hook = golem_hook)
}
```

```{r tests-my_fun}
test_that("golem_hook works", {
  
  skip_if_not_installed("golem")
  
  path_dummy_golem <- tempfile(pattern = "dummygolem")
  
  golem::create_golem(
    path = path_dummy_golem,
    open = FALSE,
    project_hook = brochure::golem_hook
  )
  
  old_wd <- setwd(path_dummy_golem)
  on.exit({
    unlink(path_dummy_golem, TRUE, TRUE)
    setwd(old_wd)
  })
  
  expect_true(
    file.exists("R/mod_home.R")
  )
  expect_true(
    file.exists("R/run_app.R")
  )
  expect_equal(
    readLines(
      system.file(
        "golem/mod_home.R",
        package = "brochure"
      )
    ),
    readLines(
      "R/mod_home.R"
    )
  )
  
  remove_app_title_line <- function(run_app_lines) {
    grep(
      pattern = "app_title = ",
      x = run_app_lines,
      value = TRUE, 
      invert = TRUE
    )
  }
  run_app_brochure_template <-readLines(
    system.file(
      "golem/run_app.R",
      package = "brochure"
    )
  )
  run_app_dummy_golem <- readLines("R/run_app.R")
  ## run_app is properly copied and...
  expect_equal(
    remove_app_title_line(run_app_brochure_template),
    remove_app_title_line(run_app_dummy_golem)
  )
  # ...app_title was modified
  expect_error(
    expect_equal(
      run_app_brochure_template,
      run_app_dummy_golem
    ),
    regexp = "app_title = "
  ) 
  
  # Module template was added in calls to golem::add_module() in 02_dev.R
  expect_true(
    grepl(
      "module_template = brochure::new_page",
      paste(readLines("dev/02_dev.R"), collapse = " ")
    )
  )
  
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_golem_hook.Rmd",
  vignette_name = NA,
  check = FALSE,
  document = FALSE
)
```

