# WARNING - Generated by {fusen} from /dev/flat_golem_hook.Rmd: do not edit by hand

test_that("golem_hook works", {
  
  skip_if_not_installed("golem")
  
  path_dummy_golem <- tempfile(pattern = "dummygolem")
  
  golem::create_golem(
    path = path_dummy_golem,
    open = FALSE,
    project_hook = brochure::golem_hook
  )
  
  old_wd <- setwd(path_dummy_golem)
  on.exit(setwd(old_wd))
  
  expect_true(
    file.exists("R/mod_home.R")
  )
  expect_true(
    file.exists("R/run_app.R")
  )
  expect_equal(
    readLines(
      system.file(
        "golem/mod_home.R",
        package = "brochure"
      )
    ),
    readLines(
      "R/mod_home.R"
    )
  )
  
  remove_app_title_line <- function(run_app_lines) {
    grep(
      pattern = "app_title = ",
      x = run_app_lines,
      value = TRUE, 
      invert = TRUE
    )
  }
  run_app_brochure_template <-readLines(
    system.file(
      "golem/run_app.R",
      package = "brochure"
    )
  )
  run_app_dummy_golem <- readLines("R/run_app.R")
  ## run_app is properly copied and...
  expect_equal(
    remove_app_title_line(run_app_brochure_template),
    remove_app_title_line(run_app_dummy_golem)
  )
  # ...app_title was modified
  expect_error(
    expect_equal(
      run_app_brochure_template,
      run_app_dummy_golem
    ),
    regexp = "app_title = "
  ) 
  
  # Module template was added in calls to golem::add_module() in 02_dev.R
  expect_true(
    grepl(
      "module_template = brochure::new_page",
      paste(readLines("dev/02_dev.R"), collapse = " ")
    )
  )
  
})
