# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

test_that("set_params works", {
  session <- shiny::MockShinySession$new()
  expect_equal(
      set_params(
        list(params = c(id = "aaa", postid = "aaa")),
        session = session
    ),
    NULL
  )
  expect_equal(
    get_params(
      session
    ),
    c(id = "aaa", postid = "aaa")
  )
})
