# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

test_that("Route works", {
  r <- Route$new(
    "/users/",
    ui = list("ui"),
    server = function(input, output, session) {
      print("server")
    }
  )
  expect_equal(
    r$path_regex,
    "^/users/$"
  )
  expect_true(
    r$matches("/users/")
  )
  expect_false(
    r$matches("/users")
  )
  expect_false(
    r$matches("/colin")
  )

  r_with_params <- Route$new(
    "/users/:id/posts/:postid",
    ui = list("ui"),
    server = function(input, output, session) {
      print("server")
    }
  )
  expect_equal(
    r_with_params$path_regex,
    "^/users/(?<id>[^/]+)/posts/(?<postid>[^/]+)$"
  )
  r_with_params$path_regex
  expect_true(
    r_with_params$matches("/users/aaa/posts/aaa")
  )
  expect_false(
    r_with_params$matches("/users")
  )
  expect_false(
    r_with_params$matches("/colin")
  )
  r_with_params$matches("/users/aaa/posts/aaa")
  extracted <- r_with_params$extract()
  expect_equal(
    unname(extracted$route),
    "/users/aaa/posts/aaa"
  )
  expect_equal(
    extracted$params,
    list(id = "aaa", postid = "aaa")
  )

  r_with_regex <- Route$new(
    "/users/posts/.*",
    ui = list("ui"),
    server = function(input, output, session) {
      print("server")
    }
  )
  expect_equal(
    r_with_regex$path_regex,
    "^/users/posts/.*$"
  )

  expect_true(
    r_with_regex$matches("/users/posts/aaa")
  )
  expect_true(
    r_with_regex$matches("/users/posts/jjj")
  )
  expect_false(
    r_with_regex$matches("/users")
  )
  expect_false(
    r_with_regex$matches("/colin")
  )

  r_with_regex$matches("/users/posts/aaa")
  extracted <- r_with_regex$extract()
  expect_equal(
    unname(extracted$route),
    "/users/posts/aaa"
  )
  expect_equal(
    extracted$params,
    list()
  )

  # Test the `initialize` method with missing arguments
  expect_error(
    Route$new(),
    'argument "href" is missing, with no default'
  )

   # Test the `matches` method with an empty route
  expect_false(
    Route$new("/users/:id",
    function() {},
    function() {})$matches("")
  )

  # Test different kind of href format
   no_backslash <- Route$new(
    "/users",
    ui = list("ui"),
    server = function(input, output, session) {
      print("server")
    }
  )
  expect_equal(
    no_backslash$path_regex,
    "^/users$"
  )
  expect_true(
    no_backslash$matches("/users")
  )
  expect_false(
    no_backslash$matches("/users/")
  )
  expect_false(
    no_backslash$matches("users/")
  )
  expect_false(
    no_backslash$matches("users")
  )

  no_slash_at_all<- Route$new(
    "users",
    ui = list("ui"),
    server = function(input, output, session) {
      print("server")
    }
  )
  expect_equal(
    no_slash_at_all$path_regex,
    "^users$"
  )
  expect_true(
    no_slash_at_all$matches("users")
  )
  expect_false(
    no_slash_at_all$matches("/users/")
  )
  expect_false(
    no_slash_at_all$matches("users/")
  )
  expect_false(
    no_slash_at_all$matches(".*")
  )

  w_regex <- Route$new(
    "/.*/",
    ui = list("ui"),
    server = function(input, output, session) {
      print("server")
    }
  )
  expect_equal(
    w_regex$path_regex,
    "^/.*/$"
  )
  expect_true(
    w_regex$matches("/users/")
  )
  expect_false(
    w_regex$matches("/users/colin")
  )
  expect_false(
    w_regex$matches("users/")
  )
  expect_false(
    w_regex$matches(".*")
  )

  w_regex_2 <- Route$new(
    "/.{1,10}/",
    ui = list("ui"),
    server = function(input, output, session) {
      print("server")
    }
  )
  expect_equal(
    w_regex_2$path_regex,
    "^/.{1,10}/$"
  )
  expect_true(
    w_regex_2$matches("/users/")
  )
  expect_false(
    w_regex_2$matches("/users/colin")
  )
  expect_false(
    w_regex_2$matches("users/")
  )
  expect_false(
    w_regex_2$matches(".*")
  )
  expect_false(
    w_regex_2$matches("/polikujyhtgfrdeswqazxcvbnm/")
  )
})
