# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

routes <- build_routes(
  list(
    list(
      href = "/users/",
      ui = list("ui"),
      server = function(input, output, session) {
        print("server")
      }
    ),
    list(
      href = "/users/:id/posts/:postid",
      ui = list("ui"),
      server = function(input, output, session) {
        print("server")
      }
    ),
    list(
      href = "/users/posts/.*",
      ui = list("ui"),
      server = function(input, output, session) {
        print("server")
      }
    ),
    list(
      href = "/users/.*/.*",
      ui = list("ui"),
      server = function(input, output, session) {
        print("server")
      }
    )
  )
)
test_that("match_route works", {
  expect_true(
    inherits(
      match_route(
        "/users/aaa/posts/aaa",
        routes
      ),
      "Route"
    )
  )
  # Checking that we match the first route
  # defined in the list, i.e "/users/posts/.*" here
  res <- match_route(
    "/users/posts/aaa/",
    routes
  )
  expect_equal(
    res$path_regex,
    "^/users/posts/.*$"
  )

})
