# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

routes <- build_routes(
  list(
    list(
      href = "/users/",
      ui = list("ui"),
      server = function(input, output, session) {
        print("server")
      }
    ),
    list(
      href = "/users/:id/posts/:postid",
      ui = list("ui"),
      server = function(input, output, session) {
        print("server")
      }
    ),
    list(
      href = "/users/posts/.*",
      ui = list("ui"),
      server = function(input, output, session) {
        print("server")
      }
    )
  )
)
test_that("build_routes works", {
  expect_true(
    length(routes) == 3
  )
  expect_true(
    all(
      vapply(
        routes,
        function(route){
          inherits(route, "Route")
        },
        logical(1)
      )
    )
  )

})
