# Generated by fusen: do not edit by hand

test_that("golem_hook works", {
  skip_if_not_installed("golem")
  old <- setwd(tempdir())
  on.exit(setwd(old))
  unlink("testgolembrochure", TRUE, TRUE)
  golem::create_golem("testgolembrochure", project_hook = brochure::golem_hook)
  setwd("testgolembrochure")
  expect_true(
    file.exists("R/page_home.R")
  )
  expect_true(
    file.exists("R/run_app.R")
  )
  expect_equal(
    readLines(
      system.file(
        "golem/page_home.R",
        package = "brochure"
      )
    ),
    readLines(
      "R/page_home.R"
    )
  )
  expect_equal(
    readLines(
      system.file(
        "golem/run_app.R",
        package = "brochure"
      )
    ),
    readLines(
      "R/run_app.R"
    )
  )
})
