# WARNING - Generated by {fusen} from /dev/flat_add_page.Rmd: do not edit by hand

test_that("golem_hook works", {
  x <- tempfile(fileext = ".R")
  new_page("pouet", x)
  
  tmplt <- readLines(
    x
  )
  expect_true(
    tmplt[1] == "#' pouet UI Function"
  )
  tmplt <- paste(tmplt, collapse = " ")
  expect_true(
    grepl("pouet", tmplt)
  )
  expect_true(
    grepl("page", tmplt)
  )
  
  skip_if_not_installed("golem")
  
  path_dummy_golem <- tempfile(pattern = "dummygolem")
  golem::create_golem(
    path = path_dummy_golem,
    open = FALSE,
    project_hook = brochure::golem_hook
  )
  
  old_wd <- setwd(path_dummy_golem)
  on.exit({
    unlink(path_dummy_golem, TRUE, TRUE)
    setwd(old_wd)
  })
  
  golem::add_module(name = "pouet", module_template = brochure::new_page)
  expect_true(
    file.exists("R/mod_pouet.R")
  )
  
})
