# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

#' Build routes from a list
#'
#' @return A list of routes
#'
#' @noRd
#' @importFrom stats setNames
#' @examples
#' routes <- build_routes(
#'   list(
#'     list(
#'       href = "/users/",
#'       ui = list("ui"),
#'       server = function(input, output, session) {
#'         print("server")
#'       }
#'     ),
#'     list(
#'       href = "/users/:id/posts/:postid",
#'       ui = list("ui"),
#'       server = function(input, output, session) {
#'         print("server")
#'       }
#'     ),
#'     list(
#'       href = "/users/posts/.*",
#'       ui = list("ui"),
#'       server = function(input, output, session) {
#'         print("server")
#'       }
#'     )
#'   )
#' )
build_routes <- function(routes){
  built_routes <- lapply(routes, function(route){
    Route$new(
      href = route$href,
      ui = route$ui,
      server = route$server
    )
  })
  setNames(
    built_routes,
    vapply(
      built_routes,
      function(route){
        route$href
      },
      character(1)
    )
  )
}
