# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

#' Match a route
#'
#' @return The matched route or FALSE
#'
#' @noRd
#' @examples
#' match_route(
#'   "/users/aaa/posts/aaa",
#'   routes
#' )
match_route <- function(
  href,
  routes
    ) {
  for (route in routes) {
    if (route$matches(href)) {
      return(route)
    }
  }
  return(FALSE)
}
