# Generated by fusen: do not edit by hand

#' Add page
#'
#' Module template for golem
#'
#' @return Used for side effect
#' @inheritParams golem::module_template
#' @export
#'
#' @examples
#' if (requireNamespace("golem") & interactive()) {
#'   golem::add_module(name = "home", module_template = brochure::new_page)
#' }
new_page <- function(name, path, export, ...) {
  tmplt <- readLines(
    system.file(
      "golem/mod_home.R",
      package = "brochure"
    )
  )
  tmplt <- gsub(
    "home",
    name,
    tmplt
  )
  tmplt <- gsub(
    "/",
    sprintf("/%s", name),
    tmplt
  )
  write(tmplt, path)
}
