# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

#' Manipulate the path params
#'
#' Set or get the path params
#'
#' @param object The object to set the params on
#' @param session The shiny session to set the params on or get from
#'
#' @return The param list as a named character vector, or NULL for set
#' @rdname params
#' @export
#' @examples
#' session <- shiny::MockShinySession$new()
#' set_params(
#'   list(params = c(id = "aaa", postid = "aaa")),
#'   session = session
#' )
#' get_params(
#'   session
#' )
set_params <- function(
  object,
  session = shiny::getDefaultReactiveDomain()
){
    session$userData$brochure_params <- object$params
    NULL
}

#' @rdname params
#' @export
get_params <- function(
  session = shiny::getDefaultReactiveDomain()
){
  session$userData$brochure_params
}
