# WARNING - Generated by {fusen} from /dev/flat_handler.Rmd: do not edit by hand

#' Route builder
#'
#' Build a shiny brochure route
#'
#' @export
#' @importFrom R6 R6Class
Route <- R6::R6Class(
  "Route",
  public = list(
    #' @field href url
    href = NULL,
    #' @field ui UI function or tagList
    ui = NULL,
    #' @field server server function
    server = NULL,
    #' @field path_regex conversion to regex
    path_regex = NULL,
    #' @field matched_route last matched route
    matched_route = NULL,
    #' @description
    #' Create a new route.
    #' @param href url
    #' @param ui UI function or tagList
    #' @param server server function
    #' @return A new `Route` object.
#' @examples
#' Route$new(
#'   "/users/",
#'   ui = list("ui"),
#'   server = function(input, output, session) {
#'     print("server")
#'   }
#' )
    initialize = function(
      href,
      ui,
      server
    ) {
      self$href <- href
      self$ui <- ui
      self$server <- server
      self$path_regex <- sprintf(
        "^%s$",
        gsub(
          ":([^/]+)",
          "(?<\\1>[^/]+)",
          href
        )
      )
    },
    #' @description
    #' Does the route object matches the url?
    #' @param route url to match
    #' @return Boolean. Does the route object matches the url?
    matches = function(route) {
      if (
        grepl(self$path_regex, route, perl = TRUE)
      ) {
        self$matched_route <- route
        return(TRUE)
      } else {
        return(FALSE)
      }
    },
    #' @description
    #' Extract the route and the parameters from the url.
    #' @return List with the route and the parameters.
    #' @param route url
    extract = function(route) {
      if (missing(route)){
        route <- self$matched_route
      }
      m <- regexec(
        self$path_regex,
          self$matched_route,
         perl = TRUE
      )
      matches <- regmatches(
        self$matched_route,
        m
      )[[1]]
      list(
        route = matches[1],
        params = as.list(matches[-1])
      )
    }
  )
)
